// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTWLtC5wZR83tHQ_whLi0uXVHCfDvorsY',
    appId: '1:780379062110:web:0f77bd05c27a8d045c19cf',
    messagingSenderId: '780379062110',
    projectId: 'emart-f6f1b',
    authDomain: 'emart-f6f1b.firebaseapp.com',
    storageBucket: 'emart-f6f1b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfgIrw0-C2CEIYPYt6CUjcfoY8Jp0Vsdw',
    appId: '1:780379062110:android:d989d83c6036f9fb5c19cf',
    messagingSenderId: '780379062110',
    projectId: 'emart-f6f1b',
    storageBucket: 'emart-f6f1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADhxor_LqkUbAMATTlg3SHxZ9s5Ew4yw8',
    appId: '1:780379062110:ios:80ced3724955c4755c19cf',
    messagingSenderId: '780379062110',
    projectId: 'emart-f6f1b',
    storageBucket: 'emart-f6f1b.firebasestorage.app',
    iosBundleId: 'com.example.emart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADhxor_LqkUbAMATTlg3SHxZ9s5Ew4yw8',
    appId: '1:780379062110:ios:80ced3724955c4755c19cf',
    messagingSenderId: '780379062110',
    projectId: 'emart-f6f1b',
    storageBucket: 'emart-f6f1b.firebasestorage.app',
    iosBundleId: 'com.example.emart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTWLtC5wZR83tHQ_whLi0uXVHCfDvorsY',
    appId: '1:780379062110:web:fe99fb110a31439e5c19cf',
    messagingSenderId: '780379062110',
    projectId: 'emart-f6f1b',
    authDomain: 'emart-f6f1b.firebaseapp.com',
    storageBucket: 'emart-f6f1b.firebasestorage.app',
  );
}
